import type { ChapterConfig } from '../types'
import { rechargeLink } from './links'

export const chapters = [
  {
    id: 'submit-cdk',
    index: '壹',
    label: '验证卡密',
    script: '验密入卷',
    title: '第一步：粘贴并验证卡密',
    summary: '在「充值提交」中粘贴店铺发送的卡密并验证。',
    coordinates: '第一步 · 充值提交',
    image: { src: './media/step-cdk.svg', alt: '操作示意：在充值提交页粘贴卡密，点击验证 CDK', position: '50% 50%', link: { ...rechargeLink, label: '打开验证卡密网站（新标签页）', region: 'button' } },
    detail: {
      kicker: '第一步 · 卡密',
      title: '提交卡密',
      intro: '卡密是这次充值的唯一钥匙，店铺发货后即可使用，长期有效。',
      quote: '① 进入【充值提交】；② 在「验证 CDK 卡密」输入框中粘贴店铺发送的卡密；③ 点击【验证 CDK】，进入 Session 提交步骤。',
      quoteAttribution: '兑换网站操作要点',
      paragraphs: [
        '卡密由店铺发出，形如一串字符。它不等订阅到期才生效——即使你的账号当前订阅尚未过期，卡密依然有效，可以拿在手中，等订阅过期显示为「free」后再来充值。',
        '验证通过后，页面会引导你进入下一步：提交 Session。请保持在同一浏览器中操作，避免中途更换设备或清空缓存。',
        '若卡密验证失败，先核对是否粘贴完整、有无多余空格；仍不成功时，携卡密截图联系店铺客服核查。',
      ],
      footnote: '验密入卷 · 第一步',
    },
  },
  {
    id: 'submit-session',
    index: '贰',
    label: '提交 Session',
    script: '取信有度',
    title: '第二步：获取并提交 Session',
    summary: '登录 ChatGPT 网页版，打开 Session 页面，全选复制后粘贴回兑换网站。',
    coordinates: 'chatgpt.com/api/auth/session',
    image: { src: './media/step-session.svg', alt: '操作示意：登录 ChatGPT 后打开 Session 页面，全选复制，再回充值网站粘贴', position: '50% 50%', link: { href: 'https://chatgpt.com/api/auth/session', label: '打开 ChatGPT Session 页面（新标签页）' } },
    detail: {
      kicker: '第二步 · 会话',
      title: '提交 Session',
      intro: 'Session 是浏览器登录后的临时会话凭证，是系统完成充值的必要凭证。',
      quote: '① 在同一浏览器登录 https://chatgpt.com/ ；② 在地址栏打开 https://chatgpt.com/api/auth/session ；③ 按 Ctrl+A 全选、Ctrl+C 复制全部内容；④ 回到兑换网站，粘贴到「提交 Session」输入框，点击【下一步】。',
      quoteAttribution: 'Session 获取四步',
      paragraphs: [
        '务必使用 Ctrl+A 全选后再复制——Session 内容很长，手动框选极易遗漏，缺一个字符都会导致提交失败。',
        'Session 不等同于账号密码，但仍属于敏感信息。请勿发送给无关人员，只粘贴到兑换网站的指定输入框。',
        '充值完成后，在 ChatGPT 网页端退出登录，当前 Session 即会失效；重新登录会生成全新的会话凭证，旧凭证随之作废。',
      ],
      footnote: '取信有度 · 第二步',
    },
  },
  {
    id: 'confirm-result',
    index: '叁',
    label: '等待完成',
    script: '守页待成',
    title: '第三步：提交任务，等待充值完成',
    summary: '确认信息无误后提交任务，保持页面打开，直到出现「充值已完成」。',
    coordinates: '兑换网站 · 任务处理中',
    image: { src: './media/step-processing.svg', alt: '状态示意：从任务处理中到充值已完成，期间保持页面打开', position: '50% 50%' },
    detail: {
      kicker: '第三步 · 静候',
      title: '确认充值结果',
      intro: '提交之后不必反复操作，系统在后台为你完成充值。',
      quote: '① 确认信息无误后提交任务，保持页面打开，等待系统处理；② 页面出现【充值已完成】后，返回 ChatGPT 网页端并刷新；③ 看到 Plus 标识或相应订阅权益，即表示充值完成。',
      quoteAttribution: '结果确认三步',
      paragraphs: [
        '处理期间请保持兑换页面打开，不要关闭或刷新。任务完成时，页面会明确显示「充值已完成」。',
        '回到 ChatGPT 网页端刷新页面，看到 Plus 标识或对应订阅权益，即为成功。',
        '若页面提示异常，请保留完整截图并联系店铺客服，客服会按售后规则核查处理。',
      ],
      footnote: '守页待成 · 第三步',
    },
  },
  {
    id: 'check-arrival',
    index: '肆',
    label: '核查到账',
    script: '查收权益',
    title: '第四步：确认 Plus 权益与邮箱账单',
    summary: '邮箱会收到订阅账单，网页端显示 Plus 权益，至此充值全部完成。',
    coordinates: '邮箱账单 · 网页权益',
    image: { src: './media/step-arrival.svg', alt: '核查示意：刷新 ChatGPT 网页端确认 Plus 权益，并核对邮箱订阅账单', position: '50% 50%', link: { href: 'https://chatgpt.com/', label: '打开 ChatGPT 核查订阅权益（新标签页）' } },
    detail: {
      kicker: '第四步 · 到账',
      title: '到账核查',
      intro: '账单与标识，是充值落定的两枚印章。',
      quote: '充值完成后，账号绑定邮箱会收到订阅账单；ChatGPT 网页版同步显示 Plus 订阅权益，二者齐备，即为到账。',
      quoteAttribution: '到账双重确认',
      paragraphs: [
        '刷新后若暂未显示 Plus，请先退出并重新登录 ChatGPT 网页端，再检查订阅状态。',
        '重新登录后仍未显示的，将兑换结果页面截图发送给客服核查，客服会协助定位原因。',
        '自查 tip：订阅状态以网页端为准，手机 App 的显示可能有缓存延迟。',
      ],
      footnote: '查收权益 · 第四步',
    },
  },
] satisfies ChapterConfig[]
